#!/usr/bin/env node

var req = require('request')
var program = require('commander')
var htmlparser = require('htmlparser2')

var ffbb = {
  search: 'http://www.ffbb.com/jouer/recherche-avancee',
  ajax: 'http://www.ffbb.com/system/ajax',
  club_lookup: 'http://www.ffbb.com/ffbb-webservice/lookup-club?cd_lbclub=',
  form_id: 'ffbb_prototype_ws_simple_form',
  form_build_id: new RegExp('<input type="hidden" name="form_build_id" value="(.+)" />\\s<input type="hidden" name="form_id" value="ffbb_prototype_ws_simple_form" />'),
  fields: { 'N': 'nom',
            'P': 'prenom',
            'S': 'sexe',
            'D': 'dtNais[date]',
            'L': 'numLicence',
            'I': 'id_license',
            'C': 'lbOrg' }
}

var parser = new htmlparser.Parser({
  onclosetag: function (name) {
    switch (name) {
      case 'h1':
      case 'h2':
      case 'h3':
        process.stdout.write('\n\n')
        break
      case 'h4':
      case 'h5':
      case 'h6':
      case 'p':
      case 'tr':
      case 'thead':
        process.stdout.write('\n')
        break
      case 'th':
      case 'td':
        process.stdout.write('\t')
    }
  },
  ontext: function (text) {
    process.stdout.write(text.trim())
  }
}, { decodeEntities: true })

program
  .command('licence')
  .description('Chercher un licencié.')
  .option('-n <nom>', 'Nom')
  .option('-p <prenom>', 'Prénom')
  .option('-s <M/F>', 'Sexe', 'M')
  .option('-d <date>', 'Date de naissance')
  .option('-l <num>', 'Numéro de licence')
  .option('-i <num>', 'Numéro national')
  .option('-c <club>', 'Club')
  .action(function (opts) {
    req(ffbb.search, function (error, res, body) {
      if (error) {
        console.log(error)
      } else if (res.statusCode !== 200) {
        console.log(res)
      } else {
        var form = {
          form_id: ffbb.form_id,
          form_build_id: ffbb.form_build_id.exec(body)[1]
        }
        for (var f in ffbb.fields) {
          form[ffbb.fields[f]] = opts[f] || ''
        }

        req.post({url: ffbb.ajax, form: form}, function (error, res, body) {
          if (error) {
            console.log(error)
          } else if (res.statusCode !== 200) {
            console.log(res)
          } else {
            var json = JSON.parse(body)
            parser.write(json.pop().data)
            parser.end()
            console.log()
          }
        })
      }
    })
  })

program
  .parse(process.argv)
